create table if not exists appointment_statuses
(
    status_id bigint generated by default as identity
        primary key,
    status_name varchar(255) not null
        unique
);

create table if not exists roles
(
    role_id bigint generated by default as identity
        primary key,
    role_name varchar(255) not null
        unique
);

create table if not exists surgeries
(
    surgery_id bigint generated by default as identity
        primary key,
    location_address varchar(255) not null,
    name varchar(255) not null,
    telephone_number varchar(255) not null
);

create table if not exists users
(
    enabled boolean not null,
    created_at timestamp(6),
    role_id bigint not null
        constraint fkp56c1712k691lhsyewcssf40f
            references roles,
    user_id bigint generated by default as identity
        primary key,
    email varchar(255) not null
        unique,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    password varchar(255) not null,
    phone_number varchar(255)
);

create table if not exists dentists
(
    user_id bigint not null
        primary key
        constraint fkhujh1sfetn2d95s56ofcd4ya
            references users,
    dentist_id_number varchar(255) not null
        unique,
    specialization varchar(255) not null
);

create table if not exists managers
(
    user_id bigint not null
        primary key
        constraint fksp1db43yf1nqhswrpbwmlnhb9
            references users,
    office_location varchar(255)
);

create table if not exists patients
(
    date_of_birth date not null,
    user_id bigint not null
        primary key
        constraint fkuwca24wcd1tg6pjex8lmc0y7
            references users,
    mailing_address text not null
);

create table if not exists appointments
(
    appointment_date_time timestamp(6) not null,
    appointment_id bigint generated by default as identity
        primary key,
    dentist_user_id bigint
        constraint fkiyrg0uvcq3qc4wgucgy1rmkgi
            references dentists,
    patient_user_id bigint
        constraint fkg9uwnqvwmu5pgfw6rhqjtvq19
            references patients,
    status_id bigint
        constraint fk856iflbp4thkpir1goxdtkcjb
            references appointment_statuses,
    surgery_id bigint
        constraint fk68v0hdkvl8qnssll24tmugia6
            references surgeries
);

create table if not exists bills
(
    amount numeric(38,2) not null,
    paid boolean not null,
    bill_id bigint generated by default as identity
        primary key,
    patient_user_id bigint
        constraint fkgbwmvtviemus2fev6o9d6lev8
            references patients
);

