spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=${SPRING_JPA_DEFAULT_SCHEMA:schema1}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}

spring.graphql.graphiql.enabled=false
server.port=${PORT:8080}

# Require external secret in cloud deployments
app.jwt.secret=${APP_JWT_SECRET}

